
POST /api/register HTTP/1.1
Host: localhost:3000
User-Agent: rest-client
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4
content-type: application/json

{
    "username": "tao test thử cái này",
    "email": "truongthanhhung@gmail.com",
    "password": "123456"
}
################################



POST /api/login HTTP/1.1
Host: localhost:3000
User-Agent: rest-client
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4
content-type: application/json

{
    "email": "truongthanhhung@gmail.com",
    "password": "123456"
}
################################