
POST /api/v1/login HTTP/1.1
Host: localhost:80
User-Agent: rest-client
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4
content-type: application/json

{
    "email": "truongpham260620@gmail.com",
    "password": "123456"
}
################################



GET /api/v1/users HTTP/1.1
Host: localhost:80
User-Agent: rest-client
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3RcL2FwaVwvdjFcL2xvZ2luIiwiaWF0IjoxNjI2MTAxMjIzLCJleHAiOjE2MjYxMDQ4MjMsIm5iZiI6MTYyNjEwMTIyMywianRpIjoieElvMXU3akh2THpSeWxWZCIsInN1YiI6MiwicHJ2IjoiMjNiZDVjODk0OWY2MDBhZGIzOWU3MDFjNDAwODcyZGI3YTU5NzZmNyJ9.Ykk7ghisbW9r8uQpmW1zyNVM0CygPw9e0G-QyUhnvrc
content-type: application/json
################################






GET /api/v1/info HTTP/1.1
Host: localhost:80
User-Agent: rest-client
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3RcL2FwaVwvdjFcL2xvZ2luIiwiaWF0IjoxNjI2MTAxMjIzLCJleHAiOjE2MjYxMDQ4MjMsIm5iZiI6MTYyNjEwMTIyMywianRpIjoieElvMXU3akh2THpSeWxWZCIsInN1YiI6MiwicHJ2IjoiMjNiZDVjODk0OWY2MDBhZGIzOWU3MDFjNDAwODcyZGI3YTU5NzZmNyJ9.Ykk7ghisbW9r8uQpmW1zyNVM0CygPw9e0G-QyUhnvrc
content-type: application/json
################################



GET /customer/ajax-demo?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3RcL2FwaVwvdjFcL2xvZ2luIiwiaWF0IjoxNjI1OTc0ODQ1LCJleHAiOjE2MjU5Nzg0NDUsIm5iZiI6MTYyNTk3NDg0NSwianRpIjoib3BoMnhaSGpSbjhsYXRBbSIsInN1YiI6MiwicHJ2IjoiMjNiZDVjODk0OWY2MDBhZGIzOWU3MDFjNDAwODcyZGI3YTU5NzZmNyJ9.SvCktIyymx71E9xoxA0Bn9pUetlj8nWM7RUMI-foRqE HTTP/1.1
Host: localhost:80
User-Agent: rest-client
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4
content-type: application/json
################################