
GET /api/test HTTP/1.1
Host: localhost:3000
User-Agent: rest-client
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4
content-type: application/json
################################



GET /api/users HTTP/1.1
Host: localhost:3000
User-Agent: rest-client
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3QiLCJpYXQiOjE2MjYxNTc3MjksImV4cCI6MTYyNjE2MTMyOSwibmJmIjoxNjI2MTU3NzI5LCJqdGkiOiJOeGx5SnBQWVl0M3VXdEp0Iiwic3ViIjozLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3IiwiYWhpaGkiOiJcdTAxMTFcdTFlZDMgbmdcdTFlZDFjIEN1c3RvbUNsYWltcyJ9.QtBCmXT4r68SYr2zIc8iPtfI2oE27VnSJw4lxg2zpYk
content-type: application/json
################################