import type { NextPage } from 'next'
import Head from 'next/head'
import Favicon from '../widgets/Favicon'
import Tophead from '../widgets/Tophead'

const Home: NextPage = () => {

  return <div className='about-page'>
    <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <Favicon />
    </Head>
    <Tophead />
</div>
}

export default Home