import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Favicon from '../widgets/Favicon'
import Nav from '../widgets/Nav'
import Tophead from '../widgets/Tophead'
import Slider from "../widgets/Slider"
import HttpStatusCode from '../constants/http.status'

/** style */
import style from "./index.module.scss"
// import styleCommon from "../styles/common.module.css"

type HomeProps = {
  notFound: boolean
  sliders: ISlider[]
}

const Home: NextPage<HomeProps> = ({ notFound, sliders } : HomeProps ) => {

  return <div className='home-page'>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <Favicon />
    </Head>
    <div className="pagecomtainer">
      <Tophead />
      <Nav />
      <div className="main">
        { notFound && <>không gọi api thành công</> }
        {
          !notFound && sliders.length && <div className={style.homeslider}><Slider data={sliders}/></div>
        }
        
        
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A ut eligendi delectus suscipit vero! Optio esse hic illum similique, excepturi consequatur architecto tempora eligendi, molestiae maxime sequi provident nulla? Deleniti.
        
      </div>
    </div>
  </div>
}

export default Home

export interface ISlider {
  _id: string
  alt: string
  topic: string
  title: string
  src: string
  excerpt: string
  content: string
  createdAt: string
  updatedAt: string
}
export async function getServerSideProps() {
  // console.log(`${process.env.API_URL}/slider`)
  try {
    const res = await fetch(`${process.env?.API_URL}/slider`)
    const response = await res.json()
    if (!response || response.code != HttpStatusCode.OK) {
      return {
        props: {
          notFound: true,
        }
      }
    }
    const sliders = response.data as ISlider[]
    return {
      props: {
        sliders
      } // will be passed to the page component as props
    }
  } catch (error) {
    return {
      notFound: true,
    }
  }
}