import type { NextPage } from 'next'
import React, { useEffect } from 'react'
import { useRouter } from 'next/router'
import Head from 'next/head'
import Image from 'next/image'
import Favicon from '../widgets/Favicon'
import Nav from '../widgets/Nav'
import Tophead from '../widgets/Tophead'

const Home: NextPage = (props: any) => {
    const router = useRouter()

    useEffect(() => {
        console.log(router.query.search)
    }, [router.query])

  return <div className='home-page'>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <Favicon />
    </Head>
    <div className="pagecomtainer">
      <Tophead />
      <Nav />
      <div className="main">
          search page
      </div>
    </div>
  </div>
}

export default Home