export default [
    {
        "id": 1,
        "fetch_link": null,
        "domain": null,
        "user_id": null,
        "name": "B\u1ea5t \u0110\u1ed9ng S\u1ea3n",
        "parent": null,
        "verify": 1,
        "slug": "bat-dong-san",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/topbds_vn.jpeg",
        "thumbnail": "\/images\/categories\/topbds_vn.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 2,
        "fetch_link": null,
        "domain": null,
        "user_id": null,
        "name": "Review - Ph\u00ea b\u00ecnh",
        "parent": null,
        "verify": 2,
        "slug": "review---phe-binh",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/review.jpeg",
        "thumbnail": "\/images\/categories\/review.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 3,
        "fetch_link": "\/forums\/thoi-trang-phu-kien.59\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "Th\u1eddi Trang - Ph\u1ee5 Ki\u1ec7n",
        "parent": null,
        "verify": 2,
        "slug": "thoi-trang---phu-kien",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/fashion.jpeg",
        "thumbnail": "\/images\/categories\/fashion.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 4,
        "fetch_link": "\/forums\/dien-thoai-linh-kien.5\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "\u0110i\u1ec7n Tho\u1ea1i - Linh Ki\u1ec7n",
        "parent": null,
        "verify": 2,
        "slug": "dien-thoai---linh-kien",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/dt-linh-kien.jpeg",
        "thumbnail": "\/images\/categories\/dt-linh-kien.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 5,
        "fetch_link": "\/forums\/lam-dep.109\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "L\u00e0m \u0110\u1eb9p",
        "parent": null,
        "verify": 2,
        "slug": "lam-dep",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/beauty.jpeg",
        "thumbnail": "\/images\/categories\/beauty.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 6,
        "fetch_link": "\/forums\/may-tinh-laptop-phu-kien.6\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "M\u00e1y T\u00ednh - Laptop - Ph\u1ee5 Ki\u1ec7n",
        "parent": null,
        "verify": 2,
        "slug": "may-tinh---laptop---phu-kien",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/may-tinh-laptop-phu-kien.jpeg",
        "thumbnail": "\/images\/categories\/may-tinh-laptop-phu-kien.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 7,
        "fetch_link": "\/forums\/dien-tu-thiet-bi-so.58\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "\u0110i\u1ec7n T\u1eed - Thi\u1ebft B\u1ecb S\u1ed1",
        "parent": null,
        "verify": 2,
        "slug": "dien-tu---thiet-bi-so",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/dien-tu-thiet-bi-so.jpeg",
        "thumbnail": "\/images\/categories\/dien-tu-thiet-bi-so.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 8,
        "fetch_link": "\/forums\/dien-may.92\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "\u0110i\u1ec7n M\u00e1y",
        "parent": null,
        "verify": 2,
        "slug": "dien-may",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/dien-may.jpeg",
        "thumbnail": "\/images\/categories\/dien-may.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 9,
        "fetch_link": "\/forums\/xe-co.21\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "Xe C\u1ed9",
        "parent": null,
        "verify": 2,
        "slug": "xe-co",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/xe-co.jpeg",
        "thumbnail": "\/images\/categories\/xe-co.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 10,
        "fetch_link": "\/forums\/phong-thuy-do-co-cay-canh-thu-nuoi.64\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "Phong Th\u1ee7y - \u0110\u1ed3 C\u1ed5 - C\u00e2y C\u1ea3nh - Th\u00fa Nu\u00f4i",
        "parent": null,
        "verify": 2,
        "slug": "phong-thuy---do-co---cay-canh---thu-nuoi",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/phong-thuy-do-co.jpeg",
        "thumbnail": "\/images\/categories\/phong-thuy-do-co.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 11,
        "fetch_link": "\/forums\/tuyen-dung-tim-viec.7\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "Tuy\u1ec3n D\u1ee5ng - T\u00ecm Vi\u1ec7c",
        "parent": null,
        "verify": 2,
        "slug": "tuyen-dung---tim-viec",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/thuyen-dung-t\u00ecm-vi\u1eb9c.jpeg",
        "thumbnail": "\/images\/categories\/thuyen-dung-t\u00ecm-vi\u1eb9c.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 12,
        "fetch_link": "\/forums\/thanh-ly-ve-chai-tap-hoa.62\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "Thanh L\u00fd - Ve Chai - T\u1ea1p H\u00f3a",
        "parent": null,
        "verify": 2,
        "slug": "thanh-ly---ve-chai---tap-hoa",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/thanh-ly-ve-chai-tap-hoa.jpeg",
        "thumbnail": "\/images\/categories\/thanh-ly-ve-chai-tap-hoa.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 13,
        "fetch_link": "\/forums\/noi-that-ngoai-that.79\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "N\u1ed9i Th\u1ea5t - Ngo\u1ea1i Th\u1ea5t",
        "parent": null,
        "verify": 2,
        "slug": "noi-that---ngoai-that",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/noi-that-ngoai-that.jpeg",
        "thumbnail": "\/images\/categories\/noi-that-ngoai-that.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 14,
        "fetch_link": "\/forums\/du-lich-am-thuc.74\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "Du L\u1ecbch - \u1ea8m Th\u1ef1c",
        "parent": null,
        "verify": 2,
        "slug": "du-lich---am-thuc",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/du-lich-am-thuc.jpeg",
        "thumbnail": "\/images\/categories\/du-lich-am-thuc.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 15,
        "fetch_link": "\/forums\/cho-game.60\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "Ch\u1ee3 Game",
        "parent": null,
        "verify": 2,
        "slug": "cho-game",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/cho-game.jpeg",
        "thumbnail": "\/images\/categories\/cho-game.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 16,
        "fetch_link": "\/forums\/dich-vu-sua-chua-cai-dat.99\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "D\u1ecbch V\u1ee5 - S\u1eeda Ch\u1eeda - C\u00e0i \u0110\u1eb7t",
        "parent": null,
        "verify": 2,
        "slug": "dich-vu---sua-chua---cai-dat",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/icon-dich-vu-sua-chua.jpeg",
        "thumbnail": "\/images\/categories\/icon-dich-vu-sua-chua.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 17,
        "fetch_link": "\/forums\/nong-lam-thuy-san.164\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "N\u00f4ng - L\u00e2m - Th\u1ee7y S\u1ea3n",
        "parent": null,
        "verify": 2,
        "slug": "nong---lam---thuy-san",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/nong-lam-thuy-san.jpeg",
        "thumbnail": "\/images\/categories\/nong-lam-thuy-san.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 18,
        "fetch_link": "\/forums\/dao-tao-khoa-hoc.168\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "\u0110\u00e0o T\u1ea1o - Kh\u00f3a H\u1ecdc",
        "parent": null,
        "verify": 2,
        "slug": "dao-tao---khoa-hoc",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/dao-tao.jpeg",
        "thumbnail": "\/images\/categories\/dao-tao.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 19,
        "fetch_link": null,
        "domain": null,
        "user_id": null,
        "name": "C\u0103n h\u1ed9 chung c\u01b0",
        "parent": 1,
        "verify": 1,
        "slug": "can-ho-chung-cu",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/can-ho-chung-cu.jpeg",
        "thumbnail": "\/images\/categories\/can-ho-chung-cu.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 20,
        "fetch_link": null,
        "domain": null,
        "user_id": null,
        "name": "Nh\u00e0 ri\u00eang",
        "parent": 1,
        "verify": 1,
        "slug": "nha-rieng",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/nha-rieng.jpeg",
        "thumbnail": "\/images\/categories\/nha-rieng.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 21,
        "fetch_link": null,
        "domain": null,
        "user_id": null,
        "name": "Nh\u00e0 bi\u1ec7t th\u1ef1, li\u1ec1n k\u1ec1",
        "parent": 1,
        "verify": 1,
        "slug": "nha-biet-thu-lien-ke",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/biet-thu.jpeg",
        "thumbnail": "\/images\/categories\/biet-thu.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 22,
        "fetch_link": null,
        "domain": null,
        "user_id": null,
        "name": "Nh\u00e0 m\u1eb7t ph\u1ed1",
        "parent": 1,
        "verify": 1,
        "slug": "nha-mat-pho",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/nha-pho.jpeg",
        "thumbnail": "\/images\/categories\/nha-pho.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 23,
        "fetch_link": null,
        "domain": null,
        "user_id": null,
        "name": "\u0110\u1ea5t n\u1ec1n d\u1ef1 \u00e1n",
        "parent": 1,
        "verify": 1,
        "slug": "dat-nen-du-an",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/dat-nen-phan-lo.jpeg",
        "thumbnail": "\/images\/categories\/dat-nen-phan-lo.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 24,
        "fetch_link": null,
        "domain": null,
        "user_id": null,
        "name": "B\u00e1n \u0111\u1ea5t",
        "parent": 1,
        "verify": 1,
        "slug": "ban-dat",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/ban-dat.jpeg",
        "thumbnail": "\/images\/categories\/ban-dat.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 25,
        "fetch_link": null,
        "domain": null,
        "user_id": null,
        "name": "Trang tr\u1ea1i, khu ngh\u1ec9 d\u01b0\u1ee1ng",
        "parent": 1,
        "verify": 1,
        "slug": "trang-trai-khu-nghi-duong",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/trai.jpeg",
        "thumbnail": "\/images\/categories\/trai.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 26,
        "fetch_link": null,
        "domain": null,
        "user_id": null,
        "name": "Kho, nh\u00e0 x\u01b0\u1edfng",
        "parent": 1,
        "verify": 1,
        "slug": "kho-nha-xuong",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/kho-xuong.jpeg",
        "thumbnail": "\/images\/categories\/kho-xuong.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 27,
        "fetch_link": null,
        "domain": null,
        "user_id": null,
        "name": "Ph\u00f2ng tr\u1ecd",
        "parent": 1,
        "verify": 1,
        "slug": "phong-tro",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/phong-tro.jpeg",
        "thumbnail": "\/images\/categories\/phong-tro.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 28,
        "fetch_link": null,
        "domain": null,
        "user_id": null,
        "name": "V\u0103n Ph\u00f2ng",
        "parent": 1,
        "verify": 1,
        "slug": "van-phong",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/van-phong.jpeg",
        "thumbnail": "\/images\/categories\/van-phong.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 29,
        "fetch_link": null,
        "domain": null,
        "user_id": null,
        "name": "M\u1eb7t b\u1eb1ng kinh doanh",
        "parent": 1,
        "verify": 1,
        "slug": "mat-bang-kinh-doanh",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/mat-bang-kinh-doanh-mat-tien.jpeg",
        "thumbnail": "\/images\/categories\/mat-bang-kinh-doanh-mat-tien.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 30,
        "fetch_link": null,
        "domain": null,
        "user_id": null,
        "name": "B\u1ea5t \u0111\u1ed9ng s\u1ea3n kh\u00e1c",
        "parent": 1,
        "verify": 1,
        "slug": "bat-dong-san-khac",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/bat-dong-san-khac.jpeg",
        "thumbnail": "\/images\/categories\/bat-dong-san-khac.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 31,
        "fetch_link": null,
        "domain": null,
        "user_id": null,
        "name": "Review - Ph\u00ea b\u00ecnh m\u00f3n \u0103n",
        "parent": 2,
        "verify": 2,
        "slug": "review---phe-binh-mon-an",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/review-food.jpeg",
        "thumbnail": "\/images\/categories\/review-food.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 32,
        "fetch_link": null,
        "domain": null,
        "user_id": null,
        "name": "Review - Ph\u00ea b\u00ecnh kh\u00e1ch s\u1ea1n",
        "parent": 2,
        "verify": 2,
        "slug": "review---phe-binh-khach-san",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/review-hotel.jpeg",
        "thumbnail": "\/images\/categories\/review-hotel.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 33,
        "fetch_link": "\/forums\/thoi-trang-nam.130\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "Th\u1eddi trang nam",
        "parent": 3,
        "verify": 2,
        "slug": "thoi-trang-nam",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/fas-male.jpeg",
        "thumbnail": "\/images\/categories\/fas-male.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 34,
        "fetch_link": "\/forums\/thoi-trang-nu.131\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "Th\u1eddi trang n\u1eef",
        "parent": 3,
        "verify": 2,
        "slug": "thoi-trang-nu",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/fas-female.jpeg",
        "thumbnail": "\/images\/categories\/fas-female.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 35,
        "fetch_link": "\/forums\/me-va-be.132\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "Th\u1eddi trang m\u1eb9 v\u00e0 b\u00e9",
        "parent": 3,
        "verify": 2,
        "slug": "thoi-trang-me-va-be",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/me-be.jpeg",
        "thumbnail": "\/images\/categories\/me-be.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 36,
        "fetch_link": "\/forums\/phu-kien.110\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "Ph\u1ee5 ki\u1ec7n th\u1eddi trang",
        "parent": 3,
        "verify": 2,
        "slug": "phu-kien-thoi-trang",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/phu-kien-thoi-trang.jpeg",
        "thumbnail": "\/images\/categories\/phu-kien-thoi-trang.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 37,
        "fetch_link": "\/forums\/iphone.115\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "Iphone",
        "parent": 4,
        "verify": 2,
        "slug": "iphone",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/iphone.jpeg",
        "thumbnail": "\/images\/categories\/iphone.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 38,
        "fetch_link": "\/forums\/android.116\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "Android",
        "parent": 4,
        "verify": 2,
        "slug": "android",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/android.jpeg",
        "thumbnail": "\/images\/categories\/android.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 39,
        "fetch_link": "\/forums\/dong-pho-thong.117\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "\u0110i\u1ec7n Tho\u1ea1i Ph\u1ed5 Th\u00f4ng",
        "parent": 4,
        "verify": 2,
        "slug": "dien-thoai-pho-thong",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/dt-pho-thong.jpeg",
        "thumbnail": "\/images\/categories\/dt-pho-thong.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 40,
        "fetch_link": "\/forums\/linh-kien.118\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "Linh ki\u1ec7n \u0111i\u1ec7n tho\u1ea1i",
        "parent": 4,
        "verify": 2,
        "slug": "linh-kien-dien-thoai",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/linh-kien-dien-thoai.jpeg",
        "thumbnail": "\/images\/categories\/linh-kien-dien-thoai.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 41,
        "fetch_link": "\/forums\/my-pham.133\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "M\u1ef9 ph\u1ea9m",
        "parent": 5,
        "verify": 2,
        "slug": "my-pham",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/my-pham.jpeg",
        "thumbnail": "\/images\/categories\/my-pham.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 42,
        "fetch_link": "\/forums\/spa.134\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "Spa",
        "parent": 5,
        "verify": 2,
        "slug": "spa",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/spa.jpeg",
        "thumbnail": "\/images\/categories\/spa.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 43,
        "fetch_link": "\/forums\/nuoc-hoa.137\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "N\u01b0\u1edbc Hoa",
        "parent": 5,
        "verify": 2,
        "slug": "nuoc-hoa",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/nuoc-hoa.jpeg",
        "thumbnail": "\/images\/categories\/nuoc-hoa.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 44,
        "fetch_link": "\/forums\/massage.135\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "Massage",
        "parent": 5,
        "verify": 2,
        "slug": "massage",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/massage.jpeg",
        "thumbnail": "\/images\/categories\/massage.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 45,
        "fetch_link": "\/forums\/may-tinh.120\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "M\u00e1y T\u00ednh",
        "parent": 6,
        "verify": 2,
        "slug": "may-tinh",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/may-tinh.jpeg",
        "thumbnail": "\/images\/categories\/may-tinh.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 46,
        "fetch_link": "\/forums\/laptop.121\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "Laptop",
        "parent": 6,
        "verify": 2,
        "slug": "laptop",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/laptop.jpeg",
        "thumbnail": "\/images\/categories\/laptop.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 47,
        "fetch_link": "\/forums\/phu-kien.122\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "Ph\u1ee5 Ki\u1ec7n",
        "parent": 6,
        "verify": 2,
        "slug": "phu-kien",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/phu-kien-lap-top.jpeg",
        "thumbnail": "\/images\/categories\/phu-kien-lap-top.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 48,
        "fetch_link": "\/forums\/do-dien-tu.138\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "\u0110\u1ed3 \u0110i\u1ec7n T\u1eed",
        "parent": 7,
        "verify": 2,
        "slug": "do-dien-tu",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/do-dien-tu.jpeg",
        "thumbnail": "\/images\/categories\/do-dien-tu.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 49,
        "fetch_link": "\/forums\/thiet-bi-so.139\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "Thi\u1ebft B\u1ecb S\u1ed1",
        "parent": 7,
        "verify": 2,
        "slug": "thiet-bi-so",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/thiet-bi-so.jpeg",
        "thumbnail": "\/images\/categories\/thiet-bi-so.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 50,
        "fetch_link": "\/forums\/linh-kien.140\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "Linh Ki\u1ec7n",
        "parent": 7,
        "verify": 2,
        "slug": "linh-kien",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/linh-kien-dien-tu.jpeg",
        "thumbnail": "\/images\/categories\/linh-kien-dien-tu.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 51,
        "fetch_link": "\/forums\/dien-gia-dung.124\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "\u0110i\u1ec7n Gia D\u1ee5ng",
        "parent": 8,
        "verify": 2,
        "slug": "dien-gia-dung",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/dien-gia-dung.jpeg",
        "thumbnail": "\/images\/categories\/dien-gia-dung.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 52,
        "fetch_link": "\/forums\/dien-lanh.125\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "\u0110i\u1ec7n L\u1ea1nh",
        "parent": 8,
        "verify": 2,
        "slug": "dien-lanh",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/dien-lanh.jpeg",
        "thumbnail": "\/images\/categories\/dien-lanh.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 53,
        "fetch_link": "\/forums\/sua-chua-thi-cong.126\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "S\u1eeda Ch\u1eefa - Thi C\u00f4ng",
        "parent": 8,
        "verify": 2,
        "slug": "sua-chua---thi-cong",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/sua-chua-thi-cong-dien-may.jpeg",
        "thumbnail": "\/images\/categories\/sua-chua-thi-cong-dien-may.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 54,
        "fetch_link": "\/forums\/xe-2-banh.141\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "Xe 2 B\u00e1nh",
        "parent": 9,
        "verify": 2,
        "slug": "xe-2-banh",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/xe-may-2-banh.jpeg",
        "thumbnail": "\/images\/categories\/xe-may-2-banh.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 55,
        "fetch_link": "\/forums\/xe-4-banh.142\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "Xe 4 B\u00e1nh",
        "parent": 9,
        "verify": 2,
        "slug": "xe-4-banh",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/oto.jpeg",
        "thumbnail": "\/images\/categories\/oto.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 56,
        "fetch_link": "\/forums\/cho-thue.143\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "Cho Thu\u00ea",
        "parent": 9,
        "verify": 2,
        "slug": "cho-thue",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/cho-thue-oto.jpeg",
        "thumbnail": "\/images\/categories\/cho-thue-oto.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 57,
        "fetch_link": "\/forums\/phu-tung-dich-vu.100\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "Ph\u1ee5 T\u00f9ng - D\u1ecbch V\u1ee5",
        "parent": 9,
        "verify": 2,
        "slug": "phu-tung---dich-vu",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/phu-tung.jpeg",
        "thumbnail": "\/images\/categories\/phu-tung.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 58,
        "fetch_link": "\/forums\/thao-luan.75\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "Th\u1ea3o Lu\u1eadn",
        "parent": 9,
        "verify": 2,
        "slug": "thao-luan",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/hoi-thao.jpeg",
        "thumbnail": "\/images\/categories\/hoi-thao.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 59,
        "fetch_link": "\/forums\/thu-nuoi.128\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "Th\u00fa Nu\u00f4i",
        "parent": 10,
        "verify": 2,
        "slug": "thu-nuoi",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/thu-nuoi.jpeg",
        "thumbnail": "\/images\/categories\/thu-nuoi.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 60,
        "fetch_link": "\/forums\/do-phong-thuy.129\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "\u0110\u1ed3 Phong Th\u1ee7y",
        "parent": 10,
        "verify": 2,
        "slug": "do-phong-thuy",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/do-phong-thuy.jpeg",
        "thumbnail": "\/images\/categories\/do-phong-thuy.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 61,
        "fetch_link": "\/forums\/cay-canh.86\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "C\u00e2y c\u1ea3nh",
        "parent": 10,
        "verify": 2,
        "slug": "cay-canh",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/van-nien-thanh.jpeg",
        "thumbnail": "\/images\/categories\/van-nien-thanh.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 62,
        "fetch_link": "\/forums\/tuyen-dung.152\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "Tuy\u1ec3n D\u1ee5ng",
        "parent": 11,
        "verify": 2,
        "slug": "tuyen-dung",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/tuyen-dung.jpeg",
        "thumbnail": "\/images\/categories\/tuyen-dung.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 63,
        "fetch_link": "\/forums\/tim-viec.153\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "T\u00ecm Vi\u1ec7c",
        "parent": 11,
        "verify": 2,
        "slug": "tim-viec",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/tim-viec.jpeg",
        "thumbnail": "\/images\/categories\/tim-viec.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 64,
        "fetch_link": "\/forums\/thanh-ly.160\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "Thanh L\u00fd",
        "parent": 12,
        "verify": 2,
        "slug": "thanh-ly",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/thanh-ly.jpeg",
        "thumbnail": "\/images\/categories\/thanh-ly.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 65,
        "fetch_link": "\/forums\/ve-chai.82\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "Ve chai",
        "parent": 12,
        "verify": 2,
        "slug": "ve-chai",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/ve-chai.jpeg",
        "thumbnail": "\/images\/categories\/ve-chai.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 66,
        "fetch_link": "\/forums\/tap-hoa.8\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "T\u1ea1p H\u00f3a",
        "parent": 12,
        "verify": 2,
        "slug": "tap-hoa",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/tap-hoa.jpeg",
        "thumbnail": "\/images\/categories\/tap-hoa.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 67,
        "fetch_link": "\/forums\/noi-that.149\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "N\u1ed9i Th\u1ea5t",
        "parent": 13,
        "verify": 2,
        "slug": "noi-that",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/noi-that.jpeg",
        "thumbnail": "\/images\/categories\/noi-that.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 68,
        "fetch_link": "\/forums\/ngoai-that.150\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "Ngo\u1ea1i Th\u1ea5t",
        "parent": 13,
        "verify": 2,
        "slug": "ngoai-that",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/ngoai-that.jpeg",
        "thumbnail": "\/images\/categories\/ngoai-that.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 69,
        "fetch_link": "\/forums\/thi-cong.151\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "Thi C\u00f4ng",
        "parent": 13,
        "verify": 2,
        "slug": "thi-cong",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/thi-cong-nha.jpeg",
        "thumbnail": "\/images\/categories\/thi-cong-nha.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 70,
        "fetch_link": "\/forums\/dia-diem-du-lich.65\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "\u0110\u1ecba \u0110i\u1ec3m Du L\u1ecbch",
        "parent": 14,
        "verify": 2,
        "slug": "dia-diem-du-lich",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/dia-diem-du-lich.jpeg",
        "thumbnail": "\/images\/categories\/dia-diem-du-lich.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 71,
        "fetch_link": "\/forums\/dia-diem-an-uong.157\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "\u0110\u1ecba \u0110i\u1ec3m \u0102n U\u1ed1ng",
        "parent": 14,
        "verify": 2,
        "slug": "dia-diem-an-uong",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/dia-diem-an-uong.jpeg",
        "thumbnail": "\/images\/categories\/dia-diem-an-uong.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 72,
        "fetch_link": "\/forums\/mua-ban-thiet-bi.154\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "Mua B\u00e1n Thi\u1ebft B\u1ecb",
        "parent": 15,
        "verify": 2,
        "slug": "mua-ban-thiet-bi",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/thiet-bi-game-thu.jpeg",
        "thumbnail": "\/images\/categories\/thiet-bi-game-thu.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 73,
        "fetch_link": "\/forums\/nap-game.155\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "N\u1ea1p Game",
        "parent": 15,
        "verify": 2,
        "slug": "nap-game",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/nap-game.jpeg",
        "thumbnail": "\/images\/categories\/nap-game.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 74,
        "fetch_link": "\/forums\/dich-vu.161\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "D\u1ecbch V\u1ee5",
        "parent": 16,
        "verify": 2,
        "slug": "dich-vu",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/cham-soc-khach-hang.jpeg",
        "thumbnail": "\/images\/categories\/cham-soc-khach-hang.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 75,
        "fetch_link": "\/forums\/sua-chua.162\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "S\u1eeda Ch\u1eefa",
        "parent": 16,
        "verify": 2,
        "slug": "sua-chua",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/thiet-bi-sua-chua.jpeg",
        "thumbnail": "\/images\/categories\/thiet-bi-sua-chua.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 76,
        "fetch_link": "\/forums\/cai-dat.163\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "C\u00e0i \u0110\u1eb7t",
        "parent": 16,
        "verify": 2,
        "slug": "cai-dat",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/cai-dat.jpeg",
        "thumbnail": "\/images\/categories\/cai-dat.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 77,
        "fetch_link": "\/forums\/nong-san.165\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "N\u00f4ng S\u1ea3n",
        "parent": 17,
        "verify": 2,
        "slug": "nong-san",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/nong-san.jpeg",
        "thumbnail": "\/images\/categories\/nong-san.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 78,
        "fetch_link": "\/forums\/lam-thuy.166\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "L\u00e2m S\u1ea3n",
        "parent": 17,
        "verify": 2,
        "slug": "lam-san",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/lam-san.jpeg",
        "thumbnail": "\/images\/categories\/lam-san.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 79,
        "fetch_link": "\/forums\/thuy-san.167\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "Th\u1ee7y S\u1ea3n",
        "parent": 17,
        "verify": 2,
        "slug": "thuy-san",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/thuy-san.jpeg",
        "thumbnail": "\/images\/categories\/thuy-san.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 80,
        "fetch_link": "\/forums\/dao-tao.169\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "\u0110\u00e0o T\u1ea1o",
        "parent": 18,
        "verify": 2,
        "slug": "dao-tao",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/training.jpeg",
        "thumbnail": "\/images\/categories\/training.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 81,
        "fetch_link": "\/forums\/giao-duc.170\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "Gi\u00e1o D\u1ee5c",
        "parent": 18,
        "verify": 2,
        "slug": "giao-duc",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/giao-duc.jpeg",
        "thumbnail": "\/images\/categories\/giao-duc.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    },
    {
        "id": 82,
        "fetch_link": "\/forums\/khoa-hoc.171\/",
        "domain": "https:\/\/cvt.vn",
        "user_id": null,
        "name": "Kh\u00f3a H\u1ecdc",
        "parent": 18,
        "verify": 2,
        "slug": "khoa-hoc",
        "excerpt": null,
        "content": null,
        "view": 1,
        "catalogue": null,
        "background": "\/images\/categories\/khoa-hoc.jpeg",
        "thumbnail": "\/images\/categories\/khoa-hoc.jpeg",
        "site_name": null,
        "image_seo": null,
        "description_seo": null,
        "extensions": "[]",
        "created_at": "2022-01-23T15:44:42.000000Z",
        "updated_at": "2022-01-23T15:44:42.000000Z"
    }
]