const TYPE =  {
    AUTH_SETTER: 'AUTH_SETTER',
    LOCATION_SETTER  : "LOCATIONS",
    
    COMMENT: {
        SETTER_COMMENT: "SETTER_COMMENT",
        ADD_COMMENT   : "ADD_COMMENT",
        LIKE_COMMENT  : "LIKE_COMMENT",
        REPORT_COMMENT: "REPORT_COMMENT",
    },
    SOCCKET  : {
        SET_SOCKET_IO: "SET_SOCKET_IO"
    },
    MESSAGE: {
        CONCAT: "CONCAT_MESSAGES_DATA",
        NEW__MESSAGE: "NEW__MESSAGE_DATA",
    }
}
export default TYPE;